
// US States and Cities mockup data
export const USStates = {
  "Alabama": ["Birmingham", "Montgomery", "Mobile", "Huntsville"],
  "Alaska": ["Anchorage", "Fairbanks", "Juneau", "Sitka"],
  "Arizona": ["Phoenix", "Tucson", "Mesa", "Chandler"],
  "Arkansas": ["Little Rock", "Fort Smith", "Fayetteville", "Springdale"],
  "California": ["Los Angeles", "San Francisco", "San Diego", "Sacramento"],
  "Colorado": ["Denver", "Colorado Springs", "Aurora", "Fort Collins"],
  "Connecticut": ["Hartford", "Bridgeport", "New Haven", "Stamford"],
  "Delaware": ["Wilmington", "Dover", "Newark", "Middletown"],
  "Florida": ["Miami", "Orlando", "Tampa", "Jacksonville"],
  "Georgia": ["Atlanta", "Savannah", "Augusta", "Columbus"],
  "Hawaii": ["Honolulu", "Hilo", "Kailua", "Kapolei"],
  "Idaho": ["Boise", "Meridian", "Nampa", "Idaho Falls"],
  "Illinois": ["Chicago", "Springfield", "Peoria", "Rockford"],
  "Indiana": ["Indianapolis", "Fort Wayne", "Evansville", "South Bend"],
  "Iowa": ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City"],
  "Kansas": ["Wichita", "Overland Park", "Kansas City", "Topeka"],
  "Kentucky": ["Louisville", "Lexington", "Bowling Green", "Owensboro"],
  "Louisiana": ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette"],
  "Maine": ["Portland", "Lewiston", "Bangor", "South Portland"],
  "Maryland": ["Baltimore", "Annapolis", "Frederick", "Rockville"],
  "Massachusetts": ["Boston", "Worcester", "Springfield", "Cambridge"],
  "Michigan": ["Detroit", "Grand Rapids", "Ann Arbor", "Lansing"],
  "Minnesota": ["Minneapolis", "Saint Paul", "Rochester", "Duluth"],
  "Mississippi": ["Jackson", "Gulfport", "Southaven", "Hattiesburg"],
  "Missouri": ["Kansas City", "St. Louis", "Springfield", "Columbia"],
  "Montana": ["Billings", "Missoula", "Great Falls", "Bozeman"],
  "Nebraska": ["Omaha", "Lincoln", "Bellevue", "Grand Island"],
  "Nevada": ["Las Vegas", "Reno", "Henderson", "North Las Vegas"],
  "New Hampshire": ["Manchester", "Nashua", "Concord", "Derry"],
  "New Jersey": ["Newark", "Jersey City", "Paterson", "Elizabeth"],
  "New Mexico": ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe"],
  "New York": ["New York City", "Buffalo", "Rochester", "Syracuse"],
  "North Carolina": ["Charlotte", "Raleigh", "Greensboro", "Durham"],
  "North Dakota": ["Fargo", "Bismarck", "Grand Forks", "Minot"],
  "Ohio": ["Columbus", "Cleveland", "Cincinnati", "Toledo"],
  "Oklahoma": ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow"],
  "Oregon": ["Portland", "Salem", "Eugene", "Gresham"],
  "Pennsylvania": ["Philadelphia", "Pittsburgh", "Allentown", "Erie"],
  "Rhode Island": ["Providence", "Warwick", "Cranston", "Pawtucket"],
  "South Carolina": ["Columbia", "Charleston", "North Charleston", "Mount Pleasant"],
  "South Dakota": ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings"],
  "Tennessee": ["Nashville", "Memphis", "Knoxville", "Chattanooga"],
  "Texas": ["Houston", "Dallas", "Austin", "San Antonio"],
  "Utah": ["Salt Lake City", "West Valley City", "Provo", "West Jordan"],
  "Vermont": ["Burlington", "South Burlington", "Rutland", "Essex Junction"],
  "Virginia": ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond"],
  "Washington": ["Seattle", "Spokane", "Tacoma", "Vancouver"],
  "West Virginia": ["Charleston", "Huntington", "Morgantown", "Parkersburg"],
  "Wisconsin": ["Milwaukee", "Madison", "Green Bay", "Kenosha"],
  "Wyoming": ["Cheyenne", "Casper", "Laramie", "Gillette"]
};
